Create answers.md
lightrainstech/join-us pull request #9
Opened 2021-03-25 17:13 UTC by aryanm1997

answers

2021-03-25 18:04 UTC, niksmac requested changes
Please fix the issues and submit again.

2021-03-25 18:04 UTC, niksmac commented on answers.md
> +2)def convert(list):
The question is to Write a function that takes a number and returns a list of its digits in an array. 
- It accepts a number like `43545` and it should return `[4, 3, 5, 4, 5]`

2021-03-25 18:04 UTC, niksmac commented on answers.md
> +3)str1=input("Enter the string:")
The question is to Remove duplicates of an array and returning an array of only unique elements 

- It accepts an array like `[4, 3, 5, 4, 5]` and it should return `[4, 3, 5]`

2021-03-26 16:17 UTC, aryanm1997 commented on answers.md
> +3)str1=input("Enter the string:")
```suggestion
3)my_list = [4,3,5,4,5]
my_final_list = set(my_list)
print(list(my_final_list))
```

2021-03-26 17:06 UTC, aryanm1997 commented on answers.md
> +2)def convert(list):
2)test_list = [4,3,5,4,5]
print ("The original list is : " +  str(test_list))
res = []
for i in test_list:
    if i not in res:
        res.append(i) 
print ("The list after removing duplicates : " + str(res))

2021-05-28 16:37 UTC, closed without merging